### ISSUE TITLE
Unclear README.md

### ISSUE THREAD

**Issue by ghost** [Asbatel/ContainerHIDS#1]
From testing and reading the source code, I don't find it very clear which files shall be in the so-called training folder. I understand it shall contain traces,seen syscalls, seen args and the max seq freq. However, the format of those and their filename are specified nowhere.
If I would like to train the model on the cb-ds dataset for example, how do I proceed?

Thanks in advance, it will save me to do some reverse eng! :)

**Comment by Asbatel** [comment]
To prepare for training, follow these steps:

1. Use the **Sysdig** tool to obtain the recording in the **.scap** format. (otherwise you can use the CB-DS or LID-DS datasets, the links can be found in the description).
2. Create a training folder and include all necessary .scap files.
3. Execute the following training command in the terminal:

    ```
    python3 main.py baseline --td training_dir (your training folder) --od output_dir (your output folder)
    ```
 
4. After executing the command, the training elements will be saved in the **.pkl** format in the specified output folder.

**Comment by VimExiter** [comment]
Thank you for your great work. I'm wondering which version of LID-DS you used. I noticed that LID-DS 2019 has a .csv file to tell whether a record is normal and LID-DS 2021 separates the dataset into training, testing and validation. I suppose that if I use the 2021 dataset I shall just use the records in the training folder as it contains only normal data, and if I use the 2019 dataset I would need to manually pick out the normal records for training. 
Another question is that I find in the CB-DS dataset 1000 scap files for normal record and 100 or 101 scap files for each attack, while the paper says 1700 for normal and 99 for each attack. I wonder what made the difference.
I'd appreciate it if you could answer my confusion😊.
